/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package vault

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/hashicorp/vault/api"
)

// AuthenticateKubernetes authenticates using the Kubernetes auth method.
// It reads the JWT from the specified tokenPath (file system).
func (c *Client) AuthenticateKubernetes(ctx context.Context, role, mountPath, tokenPath string) error {
	if mountPath == "" {
		mountPath = "kubernetes"
	}
	if tokenPath == "" {
		tokenPath = "/var/run/secrets/kubernetes.io/serviceaccount/token"
	}

	jwt, err := os.ReadFile(tokenPath)
	if err != nil {
		return fmt.Errorf("failed to read service account token: %w", err)
	}

	return c.AuthenticateKubernetesWithToken(ctx, role, mountPath, string(jwt))
}

// handleAuthResponse processes a Vault auth response — sets token, TTL, and expiration.
// All auth methods (except static token) delegate their post-login handling here.
func (c *Client) handleAuthResponse(secret *api.Secret, methodName string) error {
	if secret == nil || secret.Auth == nil {
		return fmt.Errorf("%s auth returned no token", methodName)
	}

	c.SetToken(secret.Auth.ClientToken)
	c.mu.Lock()
	c.authenticated = true
	c.tokenAccessor = secret.Auth.Accessor
	if secret.Auth.LeaseDuration > 0 {
		ttl := time.Duration(secret.Auth.LeaseDuration) * time.Second
		c.tokenTTL = ttl
		c.tokenExpiration = time.Now().Add(ttl)
	}
	c.mu.Unlock()
	return nil
}

func (c *Client) authenticateWithLoginPayload(
	ctx context.Context,
	mountPath string,
	defaultMountPath string,
	methodName string,
	loginData map[string]interface{},
) error {
	if mountPath == "" {
		mountPath = defaultMountPath
	}

	path := fmt.Sprintf("auth/%s/login", mountPath)
	secret, err := c.Logical().WriteWithContext(ctx, path, loginData)
	if err != nil {
		return fmt.Errorf("%s auth failed: %w", methodName, err)
	}

	return c.handleAuthResponse(secret, methodName)
}

// AuthenticateKubernetesWithToken authenticates using the Kubernetes auth method.
// Unlike AuthenticateKubernetes, this method accepts the JWT token directly,
// which is useful when using the TokenRequest API or other token sources.
func (c *Client) AuthenticateKubernetesWithToken(ctx context.Context, role, mountPath, jwt string) error {
	return c.authenticateWithLoginPayload(ctx, mountPath, "kubernetes", "kubernetes", map[string]interface{}{
		"role": role,
		"jwt":  jwt,
	})
}

// AuthenticateToken authenticates using a static token
func (c *Client) AuthenticateToken(token string) error {
	if token == "" {
		return fmt.Errorf("token cannot be empty")
	}
	c.SetToken(token)
	c.authenticated = true
	return nil
}

// AuthenticateAppRole authenticates using the AppRole auth method
func (c *Client) AuthenticateAppRole(ctx context.Context, roleID, secretID, mountPath string) error {
	return c.authenticateWithLoginPayload(ctx, mountPath, "approle", "approle", map[string]interface{}{
		"role_id":   roleID,
		"secret_id": secretID,
	})
}

// AuthenticateJWT authenticates using the JWT auth method.
// This is used for generic JWT-based authentication with external identity providers.
func (c *Client) AuthenticateJWT(ctx context.Context, role, mountPath, jwt string) error {
	return c.authenticateWithLoginPayload(ctx, mountPath, "jwt", "JWT", map[string]interface{}{
		"role": role,
		"jwt":  jwt,
	})
}

// AuthenticateOIDC authenticates using the OIDC auth method with a JWT token.
// This is used for workload identity (EKS OIDC, Azure AD, etc.) where the JWT
// is obtained from the K8s TokenRequest API with the OIDC issuer as the audience.
func (c *Client) AuthenticateOIDC(ctx context.Context, role, mountPath, jwt string) error {
	// Note: OIDC login uses the same endpoint format as JWT.
	return c.authenticateWithLoginPayload(ctx, mountPath, "oidc", "OIDC", map[string]interface{}{
		"role": role,
		"jwt":  jwt,
	})
}

// AuthenticateAWS authenticates using the AWS IAM auth method.
// The loginData must be pre-generated by the auth/aws helper which handles
// STS request signing using AWS SDK.
func (c *Client) AuthenticateAWS(ctx context.Context, role, mountPath string, loginData map[string]interface{}) error {
	loginData["role"] = role
	return c.authenticateWithLoginPayload(ctx, mountPath, "aws", "AWS", loginData)
}

// AuthenticateGCP authenticates using the GCP IAM auth method.
// The signedJWT must be pre-generated by the auth/gcp helper which handles
// JWT signing using GCP credentials.
func (c *Client) AuthenticateGCP(ctx context.Context, role, mountPath, signedJWT string) error {
	return c.authenticateWithLoginPayload(ctx, mountPath, "gcp", "GCP", map[string]interface{}{
		"role": role,
		"jwt":  signedJWT,
	})
}
